### ISSUE TITLE
Need to handle negative altitudes

### ISSUE THREAD

**Issue by tdicola** [adafruit/Adafruit_MPL3115A2_Library#1]
See thread here for more context: http://forums.adafruit.com/viewtopic.php?f=22&t=61365

**Comment by pepijndevos** [comment]
This seems to be fixed in 3bf551329ce6f2d5f0a17821b1e5f1606e3fd4d5?

**Comment by tintin10q** [comment]
I am still getting negative values from `baro.getAltitude();`
