### ISSUE TITLE
Asynchronous reading

### ISSUE THREAD

**Issue by Alex6735** [adafruit/Adafruit_MPL3115A2_Library#11]
Loving this board, but it takes quite a long time to read data (800 ms). I've modified the standard code to be polled and provide updated data when it is available. Are you interested in incorporating this into the standard library?

**Comment by ladyada** [comment]
yay yep you can work with @hoffmannjan to get a PR in and tested

**Comment by Alex6735** [comment]
@hoffmannjan please let me know what I need to do.

**Comment by ladyada** [comment]
you would submit a PR to start :)

**Comment by Alex6735** [comment]
Sorry - you'll have to bear with me - I'm new to using Git/GitHUB for this!

**Comment by ladyada** [comment]
see
https://learn.adafruit.com/an-introduction-to-collaborating-with-version-control
https://learn.adafruit.com/contribute-to-circuitpython-with-git-and-github

**Comment by caternuson** [comment]
Done with #26
