### ISSUE TITLE
After calling getTemperature once, pressure readings are wrong 

### ISSUE THREAD

**Issue by StevenEWright** [adafruit/Adafruit_MPL3115A2_Library#16]
- Arduino board:  Feather M0

- Arduino IDE version (found in Arduino -> About Arduino menu):  1.8.10

- List the steps to reproduce the problem below (if possible attach a sketch or
  copy the sketch code in too):

Run the `testmpl3115a2.ino` example.

After reading the temperature, the pressure readings (and altitude readings) are no longer accurate.

I modified the library locally to perform the same operation in `getTemperature` as occurs in `getPressure`, but read 5 bytes (instead of the 3 from `getPressure`), and only used the last two. This appears to fix the problem.

My modified `getTemperature` function:

```
/*!
 *  @brief  Gets the floating-point temperature in Centigrade
 *  @return temperature reading in Centigrade as a floating-point value
 */
float Adafruit_MPL3115A2::getTemperature() {
  int16_t t;

  while (read8(MPL3115A2_CTRL_REG1) & MPL3115A2_CTRL_REG1_OST)
    delay(10);

  _ctrl_reg1.bit.ALT = 1;
  write8(MPL3115A2_CTRL_REG1, _ctrl_reg1.reg);

  _ctrl_reg1.bit.OST = 1;
  write8(MPL3115A2_CTRL_REG1, _ctrl_reg1.reg);

  uint8_t sta = 0;
  while (!(sta & MPL3115A2_REGISTER_STATUS_PDR)) {
    sta = read8(MPL3115A2_REGISTER_STATUS);
    delay(10);
  }
  _i2c->beginTransmission(MPL3115A2_ADDRESS); // start transmission to device
  _i2c->write(MPL3115A2_REGISTER_PRESSURE_MSB);
  _i2c->endTransmission(false); // end transmission

  _i2c->requestFrom((uint8_t)MPL3115A2_ADDRESS,
                    (uint8_t)5);         // send data n-bytes read

  _i2c->read();
  _i2c->read();
  _i2c->read();

  t = _i2c->read();              // receive DATA
  t <<= 8;
  t |= _i2c->read(); // receive DATA
  t >>= 4;

  if (t & 0x800) {
    t |= 0xF000;
  }

  float temp = t;
  temp /= 16.0;
  return temp;
}
```

I do not know if this is the "right" fix. I don't even know if the code is at fault, or if there is a hardware issue. I do know that it is a more obvious solution when using the data sheet as a reference (see page 14/50 which contains a flow chart explaining how to get the data off the sensor via I2C). So I feel I couldn't put together a meaningful PR without spending more time on this issue.

It's possible this is the same issue as https://github.com/adafruit/Adafruit_MPL3115A2_Library/issues/8 and https://github.com/adafruit/Adafruit_MPL3115A2_Library/issues/5

**Comment by mharper** [comment]
@deanm1278 I am still seeing this problem in v1.2.4.

**Comment by deanm1278** [comment]
hey hey @mharper I'm out of the game best to try someone else

**Comment by mharper** [comment]
@deanm1278 You're gonna make me fix this myself, aren't ya? 😉

**Comment by caternuson** [comment]
For anyone still monitoring this thread - try updating to latest library release, which now uses:
https://github.com/adafruit/Adafruit_BusIO
for the underlying I2C traffic. Be sure that library is also installed.

Testing the `testmpl3115a2.ino` example in an Itsy M4 is not showing this issue:
```
Adafruit_MPL3115A2 test!
-----------------
pressure = 1005.03 hPa
altitude = 67.69 m
temperature = 25.94 C
-----------------
pressure = 1005.08 hPa
altitude = 67.56 m
temperature = 25.94 C
-----------------
pressure = 1005.08 hPa
altitude = 67.62 m
temperature = 25.94 C
```

**Comment by caternuson** [comment]
Closing for now. Can reopen if issue still exists or open new ones as needed. Hoping the BusIO update fixed these.
