### ISSUE TITLE
Large variation and slow response

### ISSUE THREAD

**Issue by hangarkat** [adafruit/Adafruit_MPL3115A2_Library#18]
Adafruit MPL3115A2
Arduino nano every

I am trying to measure rate of climb or descent. I don't care about actual altitude, just rate of change. Using command baro.getAltitude I am getting over a meter in difference between readings. I tried taking 10 readings and averaging them but this adds almost 3 seconds to the loop which defeats my purpose of looking for instantaneous rate of change.

Is there a way to quickly obtain raw pressure sensor data without temperature compensation or conversion to meters/feet/inHg?  Am I using the wrong hardware for my purpose?

Thanks for any help in advance.

SteveB
hangarkat@gmail.com

**Comment by ladyada** [comment]
you can read the pressure instead of altitude 
https://github.com/adafruit/Adafruit_MPL3115A2_Library/blob/master/Adafruit_MPL3115A2.cpp#L94
any other questions that are tech support post in the forums please. thanks!
