### ISSUE TITLE
STM32F4 based Arduino Compatible Boards

### ISSUE THREAD

**Issue by trawinlegacy** [adafruit/Adafruit_MPL3115A2_Library#19]
When trying to communicate through I2C using a STM32F4 board that is Arduino ide compatible, the WIO LTE Cat. 1 specifically, I get the following library errors:

` C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp: In member function 'float Adafruit_MPL3115A2::getPressure()':
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:95:30: error: no matching function for call to 'TwoWire::endTransmission(int)'
   _i2c->endTransmission(false); // end transmission
                              ^
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:95:30: note: candidate is:
In file included from C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:33:0:
C:\Users\liamt\AppData\Local\Arduino15\packages\Seeeduino\hardware\Seeed_STM32F4\1.2.5\libraries\Wire/Wire.h:85:11: note: uint8 TwoWire::endTransmission()
     uint8 endTransmission(void);
           ^
C:\Users\liamt\AppData\Local\Arduino15\packages\Seeeduino\hardware\Seeed_STM32F4\1.2.5\libraries\Wire/Wire.h:85:11: note:   candidate expects 0 arguments, 1 provided
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp: In member function 'float Adafruit_MPL3115A2::getAltitude()':
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:134:30: error: no matching function for call to 'TwoWire::endTransmission(int)'
   _i2c->endTransmission(false); // end transmission
                              ^
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:134:30: note: candidate is:
In file included from C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:33:0:
C:\Users\liamt\AppData\Local\Arduino15\packages\Seeeduino\hardware\Seeed_STM32F4\1.2.5\libraries\Wire/Wire.h:85:11: note: uint8 TwoWire::endTransmission()
     uint8 endTransmission(void);
           ^
C:\Users\liamt\AppData\Local\Arduino15\packages\Seeeduino\hardware\Seeed_STM32F4\1.2.5\libraries\Wire/Wire.h:85:11: note:   candidate expects 0 arguments, 1 provided
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp: In member function 'void Adafruit_MPL3115A2::setSeaPressure(float)':
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:157:30: error: no matching function for call to 'TwoWire::endTransmission(int)'
   _i2c->endTransmission(false);
                              ^
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:157:30: note: candidate is:
In file included from C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:33:0:
C:\Users\liamt\AppData\Local\Arduino15\packages\Seeeduino\hardware\Seeed_STM32F4\1.2.5\libraries\Wire/Wire.h:85:11: note: uint8 TwoWire::endTransmission()
     uint8 endTransmission(void);
           ^
C:\Users\liamt\AppData\Local\Arduino15\packages\Seeeduino\hardware\Seeed_STM32F4\1.2.5\libraries\Wire/Wire.h:85:11: note:   candidate expects 0 arguments, 1 provided
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp: In member function 'float Adafruit_MPL3115A2::getTemperature()':
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:177:30: error: no matching function for call to 'TwoWire::endTransmission(int)'
   _i2c->endTransmission(false); // end transmission
                              ^
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:177:30: note: candidate is:
In file included from C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:33:0:
C:\Users\liamt\AppData\Local\Arduino15\packages\Seeeduino\hardware\Seeed_STM32F4\1.2.5\libraries\Wire/Wire.h:85:11: note: uint8 TwoWire::endTransmission()
     uint8 endTransmission(void);
           ^
C:\Users\liamt\AppData\Local\Arduino15\packages\Seeeduino\hardware\Seeed_STM32F4\1.2.5\libraries\Wire/Wire.h:85:11: note:   candidate expects 0 arguments, 1 provided
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp: In member function 'uint8_t Adafruit_MPL3115A2::read8(uint8_t)':
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:204:30: error: no matching function for call to 'TwoWire::endTransmission(int)'
   _i2c->endTransmission(false); // end transmission
                              ^
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:204:30: note: candidate is:
In file included from C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:33:0:
C:\Users\liamt\AppData\Local\Arduino15\packages\Seeeduino\hardware\Seeed_STM32F4\1.2.5\libraries\Wire/Wire.h:85:11: note: uint8 TwoWire::endTransmission()
     uint8 endTransmission(void);
           ^
C:\Users\liamt\AppData\Local\Arduino15\packages\Seeeduino\hardware\Seeed_STM32F4\1.2.5\libraries\Wire/Wire.h:85:11: note:   candidate expects 0 arguments, 1 provided
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp: In member function 'void Adafruit_MPL3115A2::write8(uint8_t, uint8_t)':
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:222:30: error: no matching function for call to 'TwoWire::endTransmission(int)'
   _i2c->endTransmission(false); // end transmission
                              ^
C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:222:30: note: candidate is:
In file included from C:\Users\liamt\Documents\Arduino\libraries\Adafruit_MPL3115A2_Library-master\Adafruit_MPL3115A2.cpp:33:0:
C:\Users\liamt\AppData\Local\Arduino15\packages\Seeeduino\hardware\Seeed_STM32F4\1.2.5\libraries\Wire/Wire.h:85:11: note: uint8 TwoWire::endTransmission()
     uint8 endTransmission(void);
           ^
C:\Users\liamt\AppData\Local\Arduino15\packages\Seeeduino\hardware\Seeed_STM32F4\1.2.5\libraries\Wire/Wire.h:85:11: note:   candidate expects 0 arguments, 1 provided
exit status 1
Error compiling for board Wio Tracker LTE.`

**Board Details:**
https://wiki.seeedstudio.com/Wio_LTE_Cat.1/

**Board Library:**
https://github.com/Seeed-Studio/stm32f4ArduinoCore

**Code Libraries:**
https://github.com/SeeedJP/WioLTEforArduino
https://github.com/adafruit/Adafruit_MPL3115A2_Library

**Comment by ladyada** [comment]
please ask seed to fix their STM32F4 core to match the Arduino standard, then this and all other libraries will work.
