### ISSUE TITLE
Incorrect pressure readings

### ISSUE THREAD

**Issue by hdtodd** [adafruit/Adafruit_MPL3115A2_Library#5]
Using commit 4d49b66ef4 and testing with examples/testmpl3115A2, I get incorrect pressures, at least after the first reading: see failure PNG.  Corrected by reading the pressure MBR register _before_ initiating new read, to clear PDR bit: see "corrected" PNG.  Added the line 
    read8(MPL3115A2_REGISTER_PRESSURE_MSB);
as the first executable statement in getPressure() to make this change.  There are other changes needed to make the MPL3115A2 library more bullet-proof, but this solves the obvious one.

Will try to figure out how to merge  my edit to this base with master and upload for consideration for incorporation.  But for those who get to this issue, maybe this simple fix will help.

![adafruit_mpl3115a2_test_failure_demo](https://cloud.githubusercontent.com/assets/5464284/8666904/0e68fad2-29b5-11e5-8f0a-2ee0c10ed397.png)
![adafruit_mpl3115a2_test_corrected_demo](https://cloud.githubusercontent.com/assets/5464284/8666905/12e8a60c-29b5-11e5-8468-c3b86024ab7d.png)

**Comment by ghost** [comment]
I just ran into this very problem. I solved it by doing two reads, throwing away the first. This would be a nice bug fix as right now its doubling the time to read such a wonderful little module.

**Comment by hdtodd** [comment]
I ended up revising the code to use Wayne Truchsess's I2C Library code in place of the Wire library.  I haven't studied all the technical details, but it seems that Freescale is inclined to use "repeated START" in its I2C devices (problems reported using Wire with other Freescale devices), and the standard Arduino Wire library doesn't handle that well.  I2CLibrary does.  So I'm able to monitor several I2C devices over a long period of time with no data corruption.  I've got the code for Chronodot and MPL3115A2 on my github site: you're welcome to it.  I've sent a link to SparkFun, too, in case they want to pick it up.  -David

**Comment by ghost** [comment]
Thanks, David. I will give a look here soon.

**Comment by deanm1278** [comment]
hey we've made a bunch of updates to this lib, if this is still a problem please open another issue and let us know :)

**Comment by hdtodd** [comment]
Thanks, Dean: I'll give it a look.
