### ISSUE TITLE
Reading issues

### ISSUE THREAD

**Issue by beicnet** [adafruit/Adafruit_MPL3115A2_Library#8]
The readings only works if I request the `getPressure()` **first**, in any other combination it will not work.

Example (this will read nothing):
```
float mpl_t = mpl.getTemperature();
float mpl_p = mpl.getPressure() / 100.0;
float mpl_a = mpl.getAltitude();
```
and this will work, why?
```
float mpl_p = mpl.getPressure() / 100.0;
float mpl_t = mpl.getTemperature();
float mpl_a = mpl.getAltitude();
```

**Comment by charlesalexanderlee** [comment]
Having the same issue here. Why has this not been fixed yet?

**Comment by caternuson** [comment]
Please try the 1.2.2 version of the library when it becomes available.
https://github.com/adafruit/Adafruit_MPL3115A2_Library/releases/tag/1.2.2
